/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static ui.DBconnection.con;

/**
 *
 * @author 91983
 */
public class Home_Page extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pre= null;
    ResultSet res = null;
    static int ex;
    User user ;
    Company comp;
    static Drug drug ;
    static Move_Drug move_drug;
    Buy_Drug buy;
    Date d;
    SimpleDateFormat dd;
    static String to;
    static String from ;
    static String text ;
    static String almost_expired_bar ;
    static String expired_bar ;
    

    /**
     * Creates new form Home_Page
     */
    public Home_Page() {
        initComponents();
        con=DBconnection.getConnection();
   //     showDate();
        buttonvis();
        user = new User();
        drug = new Drug();
        comp = new Company();
        move_drug = new Move_Drug();
        buy = new Buy_Drug();
  //      loginas();
        warning();
        login_as();
        alert_message();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        setting = new java.awt.Button();
        purchase = new java.awt.Button();
        drugdetails = new java.awt.Button();
        company = new java.awt.Button();
        userB = new java.awt.Button();
        sales = new java.awt.Button();
        drugs = new java.awt.Button();
        newcom = new java.awt.Button();
        logout = new java.awt.Button();
        logindetails = new java.awt.Button();
        buydrug = new java.awt.Button();
        changepass = new java.awt.Button();
        update = new java.awt.Button();
        endwith = new java.awt.Button();
        alldeals = new java.awt.Button();
        updatedeals = new java.awt.Button();
        checkplace = new java.awt.Button();
        adduser = new java.awt.Button();
        updateuser = new java.awt.Button();
        deleteuser = new java.awt.Button();
        renew_validate = new java.awt.Button();
        expired1 = new java.awt.Button();
        editprice = new java.awt.Button();
        almost = new java.awt.Button();
        searchdrug = new java.awt.Button();
        updatedrug = new java.awt.Button();
        deletedrug = new java.awt.Button();
        movedrug1 = new java.awt.Button();
        adddrug = new java.awt.Button();
        movedrug = new java.awt.Button();
        salesbill = new java.awt.Button();
        retdrug = new java.awt.Button();
        shiftsales = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Drug Management");

        setting.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        setting.setLabel("Settings");
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        purchase.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        purchase.setLabel("Purchase");
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });

        drugdetails.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        drugdetails.setLabel("Drug Details");
        drugdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugdetailsActionPerformed(evt);
            }
        });

        company.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        company.setLabel("Company");
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });

        userB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userB.setLabel("User");
        userB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBActionPerformed(evt);
            }
        });

        sales.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sales.setLabel("Sales");
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });

        drugs.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        drugs.setLabel("Drugs");
        drugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugsActionPerformed(evt);
            }
        });

        newcom.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        newcom.setLabel("New Comapny");
        newcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcomActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        logout.setLabel("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        logindetails.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        logindetails.setLabel("Login Details");
        logindetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logindetailsActionPerformed(evt);
            }
        });

        buydrug.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buydrug.setLabel("Buy Drugs");
        buydrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buydrugActionPerformed(evt);
            }
        });

        changepass.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        changepass.setLabel("Change Password");
        changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        update.setLabel("Updates");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        endwith.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        endwith.setLabel("End Width");
        endwith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endwithActionPerformed(evt);
            }
        });

        alldeals.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        alldeals.setLabel("All Deals");
        alldeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alldealsActionPerformed(evt);
            }
        });

        updatedeals.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        updatedeals.setLabel("Update Deals");
        updatedeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedealsActionPerformed(evt);
            }
        });

        checkplace.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        checkplace.setLabel("Check Places");
        checkplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkplaceActionPerformed(evt);
            }
        });

        adduser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        adduser.setLabel("Add User");
        adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserActionPerformed(evt);
            }
        });

        updateuser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        updateuser.setLabel("Update user");
        updateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateuserActionPerformed(evt);
            }
        });

        deleteuser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deleteuser.setLabel("Delete User");
        deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuserActionPerformed(evt);
            }
        });

        renew_validate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        renew_validate.setLabel("Renew Validity");
        renew_validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renew_validateActionPerformed(evt);
            }
        });

        expired1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        expired1.setLabel("Expired Drugs");
        expired1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expired1ActionPerformed(evt);
            }
        });

        editprice.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        editprice.setLabel("Edit Prices");
        editprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpriceActionPerformed(evt);
            }
        });

        almost.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        almost.setLabel("Less Stock");
        almost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almostActionPerformed(evt);
            }
        });

        searchdrug.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        searchdrug.setLabel("Search Drug");
        searchdrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdrugActionPerformed(evt);
            }
        });

        updatedrug.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        updatedrug.setLabel("Update Drug");
        updatedrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedrugActionPerformed(evt);
            }
        });

        deletedrug.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deletedrug.setLabel("Delete Drug");
        deletedrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedrugActionPerformed(evt);
            }
        });

        movedrug1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        movedrug1.setLabel("Move Drug");
        movedrug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movedrug1ActionPerformed(evt);
            }
        });

        adddrug.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        adddrug.setLabel("Add Drug");
        adddrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddrugActionPerformed(evt);
            }
        });

        movedrug.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        movedrug.setLabel("Drug List");
        movedrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movedrugActionPerformed(evt);
            }
        });

        salesbill.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        salesbill.setLabel("Sales Bill");
        salesbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesbillActionPerformed(evt);
            }
        });

        retdrug.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        retdrug.setLabel("Retrieval Drug");
        retdrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retdrugActionPerformed(evt);
            }
        });

        shiftsales.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        shiftsales.setLabel("Shift Sales");
        shiftsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftsalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logindetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setting, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(changepass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endwith, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(newcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(retdrug, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shiftsales, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salesbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alldeals, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buydrug, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(editprice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(almost, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(expired1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(updatedrug, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(movedrug1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(movedrug, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(renew_validate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(47, 47, 47)
                                        .addComponent(searchdrug, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deletedrug, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(checkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adddrug, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(sales, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updatedeals, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(drugdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(drugs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setting, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sales, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(buydrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(68, 68, 68))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(updatedeals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(alldeals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(logindetails, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(88, 88, 88))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(salesbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(shiftsales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(retdrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(newcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(changepass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(endwith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(432, 432, 432))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(adddrug, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletedrug, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updatedrug, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchdrug, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(movedrug1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(movedrug, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(checkplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editprice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(expired1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(renew_validate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(almost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(452, 452, 452))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1004, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1914, 1032));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
                company();

    }//GEN-LAST:event_companyActionPerformed

    private void userBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userBActionPerformed

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
        // TODO add your handling code here:
        sales();
    }//GEN-LAST:event_salesActionPerformed

    private void drugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugsActionPerformed

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        // TODO add your handling code here:
        if(!username.getText().equals("Employee")){
            enterpurchase();
        }else {
            String pass = JOptionPane.showInputDialog("You are not allowed to check user Inforamtion\nTo get in please confirm Admin Password");
            String sql = "select NAME,PASSWORD from users where NAME='Ebrahem Samer' ";
            
            if (!pass.equals("")) {
                
                try{
                    pre=con.prepareStatement(sql);
                    res=pre.executeQuery();
                    if(res.next()){
                        if(res.getString("PASSWORD").equals(pass)){
                            enterpurchase();
                        }else if(pass.isEmpty()){
                            JOptionPane.showMessageDialog(null,"You must write admin Password","Failed Access",2);
                        }else {
                            JOptionPane.showMessageDialog(null,"Wrong Password","Failed Access",2);
                        }}
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
                }
            } else {
                JOptionPane.showMessageDialog(null,"Please type in Admin Password","Failed Access",2);
                
            }
            
        }
    }//GEN-LAST:event_purchaseActionPerformed

    private void newcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcomActionPerformed
        // TODO add your handling code here:
        comp.setVisible(true);
        comp.addNewCompany();
       
//       comp.update.setEnabled(false);
//       comp.delete.setEnabled(false);
    }//GEN-LAST:event_newcomActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void logindetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logindetailsActionPerformed
        // TODO add your handling code here:
                new Login_Details().setVisible(true);

    }//GEN-LAST:event_logindetailsActionPerformed

    private void buydrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buydrugActionPerformed
        // TODO add your handling code here:
        buy.setVisible(true);
        buy.makedeal.setEnabled(true);
        buy.update.setEnabled(false);
    }//GEN-LAST:event_buydrugActionPerformed

    private void changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassActionPerformed
        // TODO add your handling code here:
                new Change_Password().setVisible(true);

    }//GEN-LAST:event_changepassActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        comp.setVisible(true);
        comp.updateCompany();
    }//GEN-LAST:event_updateActionPerformed

    private void endwithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endwithActionPerformed
        // TODO add your handling code here:
        comp.setVisible(true);
        comp.deleteCompany();
    }//GEN-LAST:event_endwithActionPerformed

    private void alldealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alldealsActionPerformed
        // TODO add your handling code here:
        new All_Deal().setVisible(true);
    }//GEN-LAST:event_alldealsActionPerformed

    private void updatedealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedealsActionPerformed
        // TODO add your handling code here:
        buy.setVisible(true);
        buy.update.setEnabled(true);
        buy.makedeal.setEnabled(false);
    }//GEN-LAST:event_updatedealsActionPerformed

    private void checkplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkplaceActionPerformed
        // TODO add your handling code here:
        new Move_Drug().setVisible(true);
    }//GEN-LAST:event_checkplaceActionPerformed

    private void adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserActionPerformed
        // TODO add your handling code here:
         user.setVisible(true);
        user.deleteuser.setEnabled(false);
        user.updateuser.setEnabled(false);
        user.adduser.setEnabled(true);
    }//GEN-LAST:event_adduserActionPerformed

    private void updateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateuserActionPerformed
        // TODO add your handling code here:
         user.setVisible(true);
        user.deleteuser.setEnabled(false);
        user.adduser.setEnabled(false);
        user.updateuser.setEnabled(true);
        user.id.setEditable(false);
    }//GEN-LAST:event_updateuserActionPerformed

    private void deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuserActionPerformed
        // TODO add your handling code here:
         user.setVisible(true);
        user.adduser.setEnabled(false);
        user.updateuser.setEnabled(false);
        user.deleteuser.setEnabled(true);
    }//GEN-LAST:event_deleteuserActionPerformed

    private void renew_validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renew_validateActionPerformed
        // TODO add your handling code here:
        new Renew_Validity().setVisible(true);
    }//GEN-LAST:event_renew_validateActionPerformed

    private void expired1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expired1ActionPerformed
        // TODO add your handling code here:
        new Expired_Drug().setVisible(true);
    }//GEN-LAST:event_expired1ActionPerformed

    private void editpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpriceActionPerformed
        // TODO add your handling code here:
        new Edit_Price().setVisible(true);
    }//GEN-LAST:event_editpriceActionPerformed

    private void almostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almostActionPerformed
        // TODO add your handling code here:
        new Almost_Finish().setVisible(true);
    }//GEN-LAST:event_almostActionPerformed

    private void searchdrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdrugActionPerformed
        // TODO add your handling code here:
        new Search_Drug().setVisible(true);
    }//GEN-LAST:event_searchdrugActionPerformed

    private void updatedrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedrugActionPerformed
        // TODO add your handling code here:
        drug.setVisible(true);
        drug.adddrug.setEnabled(false);
        drug.deletedrug.setEnabled(false);
        drug.updatedrug.setEnabled(true);
    }//GEN-LAST:event_updatedrugActionPerformed

    private void deletedrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedrugActionPerformed
        // TODO add your handling code here:
        drug.setVisible(true);
        drug.updatedrug.setEnabled(false);
        drug.adddrug.setEnabled(false);
        drug.deletedrug.setEnabled(true);
    }//GEN-LAST:event_deletedrugActionPerformed

    private void movedrug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movedrug1ActionPerformed
        // TODO add your handling code here:
        new Move_Drug().setVisible(true);
    }//GEN-LAST:event_movedrug1ActionPerformed

    private void adddrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddrugActionPerformed
        // TODO add your handling code here:
        drug.setVisible(true);
        drug.updatedrug.setEnabled(false);
        drug.deletedrug.setEnabled(false);
        drug.adddrug.setEnabled(true);

    }//GEN-LAST:event_adddrugActionPerformed

    private void movedrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movedrugActionPerformed
        // TODO add your handling code here:
        new Drug_List().setVisible(true);
    }//GEN-LAST:event_movedrugActionPerformed

    private void salesbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesbillActionPerformed
        // TODO add your handling code here:
        new Sales_Bill().setVisible(true);
    }//GEN-LAST:event_salesbillActionPerformed

    private void retdrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retdrugActionPerformed
        // TODO add your handling code here:
        new Retrieval_Drug().setVisible(true);
    }//GEN-LAST:event_retdrugActionPerformed

    private void shiftsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftsalesActionPerformed
        // TODO add your handling code here:
        new Shift_Sales().setVisible(true);
    }//GEN-LAST:event_shiftsalesActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
                setting();

    }//GEN-LAST:event_settingActionPerformed

    private void drugdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugdetailsActionPerformed
        // TODO add your handling code here:
         enterdrugdetails();
    }//GEN-LAST:event_drugdetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button adddrug;
    private java.awt.Button adduser;
    private java.awt.Button alldeals;
    private java.awt.Button almost;
    private java.awt.Button buydrug;
    private java.awt.Button changepass;
    private java.awt.Button checkplace;
    private java.awt.Button company;
    private java.awt.Button deletedrug;
    private java.awt.Button deleteuser;
    private java.awt.Button drugdetails;
    private java.awt.Button drugs;
    private java.awt.Button editprice;
    private java.awt.Button endwith;
    private java.awt.Button expired1;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private java.awt.Button logindetails;
    private java.awt.Button logout;
    private java.awt.Button movedrug;
    private java.awt.Button movedrug1;
    private java.awt.Button newcom;
    private java.awt.Button purchase;
    private java.awt.Button renew_validate;
    private java.awt.Button retdrug;
    private java.awt.Button sales;
    private java.awt.Button salesbill;
    private java.awt.Button searchdrug;
    private java.awt.Button setting;
    private java.awt.Button shiftsales;
    private java.awt.Button update;
    private java.awt.Button updatedeals;
    private java.awt.Button updatedrug;
    private java.awt.Button updateuser;
    private java.awt.Button userB;
    // End of variables declaration//GEN-END:variables
//private void showDate(){
  //      d = new Date();
    //    dd = new SimpleDateFormat("dd-MM-yyyy");
      //  today.setText(dd.format(d));
        
//        new Timer(0,new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent ae) {
  //              Date d = new Date();
  //              SimpleDateFormat dd = new SimpleDateFormat("hh:mm:ss a");
    //            time.setText(dd.format(d));
      //      }
   //     }).start();
   // }
    private void buttonvis(){
        adduser.setVisible(false);
        deleteuser.setVisible(false);
        updateuser.setVisible(false);
        
        adddrug.setVisible(false);
        deletedrug.setVisible(false);
        updatedrug.setVisible(false);
        searchdrug.setVisible(false);
        movedrug.setVisible(false);
        movedrug1.setVisible(false);
        
        checkplace.setVisible(false);
        editprice.setVisible(false);
        renew_validate.setVisible(false);
        expired1.setVisible(false);
        almost.setVisible(false);
        
        buydrug.setVisible(false);
        updatedeals.setVisible(false);
        alldeals.setVisible(false);
        
        salesbill.setVisible(false);
        shiftsales.setVisible(false);
        retdrug.setVisible(false);
        
        newcom.setVisible(false);
        endwith.setVisible(false);
        update.setVisible(false);
        
        logindetails.setVisible(false);
        changepass.setVisible(false);
        logout.setVisible(false);
    }
    private void uservis(){
        adduser.setVisible(true);
        deleteuser.setVisible(true);
        updateuser.setVisible(true);
        
    }
    private void enteruser(){
        userB.setEnabled(false);
        drugs.setEnabled(true);
        drugdetails.setEnabled(true);
        sales.setEnabled(true);
        purchase.setEnabled(true);
        setting.setEnabled(true);
        company.setEnabled(true);
        
        adduser.setVisible(true);
        deleteuser.setVisible(true);
        updateuser.setVisible(true);
        
        adddrug.setVisible(false);
        deletedrug.setVisible(false);
        updatedrug.setVisible(false);
        searchdrug.setVisible(false);
        movedrug.setVisible(false);
        movedrug1.setVisible(false);
        
        editprice.setVisible(false);
        checkplace.setVisible(false);
        renew_validate.setVisible(false);
        expired1.setVisible(false);
        almost.setVisible(false);
        
        buydrug.setVisible(false);
        updatedeals.setVisible(false);
        alldeals.setVisible(false);
        
        salesbill.setVisible(false);
        shiftsales.setVisible(false);
        retdrug.setVisible(false);
        
        newcom.setVisible(false);
        endwith.setVisible(false);
        update.setVisible(false);
        
        logindetails.setVisible(false);
        changepass.setVisible(false);
        logout.setVisible(false);
    }
    private void enterdrugs(){
        drugs.setEnabled(false);
        userB.setEnabled(true);
        drugdetails.setEnabled(true);
        sales.setEnabled(true);
        purchase.setEnabled(true);
        setting.setEnabled(true);
        company.setEnabled(true);
        
        adduser.setVisible(false);
        deleteuser.setVisible(false);
        updateuser.setVisible(false);
        
        adddrug.setVisible(true);
        deletedrug.setVisible(true);
        updatedrug.setVisible(true);
        searchdrug.setVisible(true);
        movedrug.setVisible(true);
        movedrug1.setVisible(true);
        
        editprice.setVisible(false);
        checkplace.setVisible(false);
        renew_validate.setVisible(false);
        expired1.setVisible(false);
        almost.setVisible(false);
        
        buydrug.setVisible(false);
        updatedeals.setVisible(false);
        alldeals.setVisible(false);
        
        salesbill.setVisible(false);
        shiftsales.setVisible(false);
        retdrug.setVisible(false);
        
        newcom.setVisible(false);
        endwith.setVisible(false);
        update.setVisible(false);
        
        logindetails.setVisible(false);
        changepass.setVisible(false);
        logout.setVisible(false);
    }
    private void enterdrugdetails(){
        drugdetails.setEnabled(false);
        userB.setEnabled(true);
        drugs.setEnabled(true);
        sales.setEnabled(true);
        purchase.setEnabled(true);
        setting.setEnabled(true);
        company.setEnabled(true);
        
        adduser.setVisible(false);
        deleteuser.setVisible(false);
        updateuser.setVisible(false);
        
        adddrug.setVisible(false);
        deletedrug.setVisible(false);
        updatedrug.setVisible(false);
        searchdrug.setVisible(false);
        movedrug.setVisible(false);
        movedrug1.setVisible(false);
        
        editprice.setVisible(true);
        checkplace.setVisible(true);
        renew_validate.setVisible(true);
        expired1.setVisible(true);
        almost.setVisible(true);
        
        buydrug.setVisible(false);
        updatedeals.setVisible(false);
        alldeals.setVisible(false);
        
        salesbill.setVisible(false);
        shiftsales.setVisible(false);
        retdrug.setVisible(false);
        
        newcom.setVisible(false);
        endwith.setVisible(false);
        update.setVisible(false);
        
        logindetails.setVisible(false);
        changepass.setVisible(false);
        logout.setVisible(false);
    }
    private void enterpurchase(){
        purchase.setEnabled(false);
        userB.setEnabled(true);
        drugs.setEnabled(true);
        drugdetails.setEnabled(true);
        sales.setEnabled(true);
        setting.setEnabled(true);
        company.setEnabled(true);
        
        adduser.setVisible(false);
        deleteuser.setVisible(false);
        updateuser.setVisible(false);
        
        adddrug.setVisible(false);
        deletedrug.setVisible(false);
        updatedrug.setVisible(false);
        searchdrug.setVisible(false);
        movedrug.setVisible(false);
        movedrug1.setVisible(false);
        
        editprice.setVisible(false);
        checkplace.setVisible(false);
        renew_validate.setVisible(false);
        expired1.setVisible(false);
        almost.setVisible(false);
        
        buydrug.setVisible(true);
        updatedeals.setVisible(true);
        alldeals.setVisible(true);
        
        salesbill.setVisible(false);
        shiftsales.setVisible(false);
        retdrug.setVisible(false);
        
        newcom.setVisible(false);
        endwith.setVisible(false);
        update.setVisible(false);
        
        logindetails.setVisible(false);
        changepass.setVisible(false);
        logout.setVisible(false);
    }
    private void sales(){
        sales.setEnabled(false);
        userB.setEnabled(true);
        drugs.setEnabled(true);
        drugdetails.setEnabled(true);
        purchase.setEnabled(true);
        setting.setEnabled(true);
        company.setEnabled(true);
        
        adduser.setVisible(false);
        deleteuser.setVisible(false);
        updateuser.setVisible(false);
        
        adddrug.setVisible(false);
        deletedrug.setVisible(false);
        updatedrug.setVisible(false);
        searchdrug.setVisible(false);
        movedrug.setVisible(false);
        movedrug1.setVisible(false);
        
        editprice.setVisible(false);
        checkplace.setVisible(false);
        renew_validate.setVisible(false);
        expired1.setVisible(false);
        almost.setVisible(false);
        
        buydrug.setVisible(false);
        updatedeals.setVisible(false);
        alldeals.setVisible(false);
        
        salesbill.setVisible(true);
        shiftsales.setVisible(true);
        retdrug.setVisible(true);
        
        newcom.setVisible(false);
        endwith.setVisible(false);
        update.setVisible(false);
        
        logindetails.setVisible(false);
        changepass.setVisible(false);
        logout.setVisible(false);
    }
    private void setting(){
        setting.setEnabled(false);
        userB.setEnabled(true);
        drugs.setEnabled(true);
        drugdetails.setEnabled(true);
        sales.setEnabled(true);
        purchase.setEnabled(true);
        company.setEnabled(true);
        
        adduser.setVisible(false);
        deleteuser.setVisible(false);
        updateuser.setVisible(false);
        
        adddrug.setVisible(false);
        deletedrug.setVisible(false);
        updatedrug.setVisible(false);
        searchdrug.setVisible(false);
        movedrug.setVisible(false);
        movedrug1.setVisible(false);
        
        editprice.setVisible(false);
        checkplace.setVisible(false);
        renew_validate.setVisible(false);
        expired1.setVisible(false);
        almost.setVisible(false);
        
        buydrug.setVisible(false);
        updatedeals.setVisible(false);
        alldeals.setVisible(false);
        
        salesbill.setVisible(false);
        shiftsales.setVisible(false);
        retdrug.setVisible(false);
        
        newcom.setVisible(false);
        endwith.setVisible(false);
        update.setVisible(false);
        
        logindetails.setVisible(true);
        changepass.setVisible(true);
        logout.setVisible(true);
    }
    private void company(){
        company.setEnabled(false);
        userB.setEnabled(true);
        drugs.setEnabled(true);
        drugdetails.setEnabled(true);
        sales.setEnabled(true);
        purchase.setEnabled(true);
        setting.setEnabled(true);
        
        adduser.setVisible(false);
        deleteuser.setVisible(false);
        updateuser.setVisible(false);
        
        adddrug.setVisible(false);
        deletedrug.setVisible(false);
        updatedrug.setVisible(false);
        searchdrug.setVisible(false);
        movedrug.setVisible(false);
        movedrug1.setVisible(false);
        
        editprice.setVisible(false);
        checkplace.setVisible(false);
        renew_validate.setVisible(false);
        expired1.setVisible(false);
        almost.setVisible(false);
        
        buydrug.setVisible(false);
        updatedeals.setVisible(false);
        alldeals.setVisible(false);
        
        salesbill.setVisible(false);
        shiftsales.setVisible(false);
        retdrug.setVisible(false);
        
        newcom.setVisible(true);
        endwith.setVisible(true);
        update.setVisible(true);
        
        logindetails.setVisible(false);
        changepass.setVisible(false);
        logout.setVisible(false);
    }
    //private void loginas(){
    //    String sql = "select ID,NAME from users where ID='"+Login.id.getText()+"' ";
      //  try{
     //       pre=con.prepareStatement(sql);
       //     res=pre.executeQuery();
         //   if(res.next()){
   //             username1.setText(res.getString("NAME"));
   //        //     if(res.getString("ID").equals("1")){
    //                username.setText("Admin");
    //            }else{
     //               username.setText("Employee");
    //            }
    //        }
     //   }catch(Exception e){
     //       JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
     //   }
  //  }
    private void warning(){
        //check the Expiration of the drugs;
        
        int ex_year ;
        int current_year ;
        int ex_month ;
        int ex_day ;
        int current_month ;
        int current_day ;
        String sql = "select BARCODE,EXPIRATION_DATE from drugs";
        try{
            pre=con.prepareStatement(sql);
            res=pre.executeQuery();
            while(res.next()){
                Warning warning = new Warning();
                ex_year = Integer.parseInt(res.getString("EXPIRATION_DATE").split("-")[2]);
                ex_month = Integer.parseInt(res.getString("EXPIRATION_DATE").split("-")[1]);
                ex_day = Integer.parseInt(res.getString("EXPIRATION_DATE").split("-")[0]);
                current_year = Integer.parseInt(dd.format(d).split("-")[2]);
                current_month = Integer.parseInt(dd.format(d).split("-")[1]);
                current_day = Integer.parseInt(dd.format(d).split("-")[0]);
                if(ex_year==current_year){
                    if(ex_month-current_month==2){
                        ex=1;
                        almost_expired_bar = res.getString("BARCODE");
                        warning.setVisible(true);
                    }else if(ex_month==current_month){
                        if(ex_day==current_day){
                            ex=0;
                            expired_bar = res.getString("BARCODE");
                            update_to_expired();
                            warning.setVisible(true);
                        }
                    }
                }
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
            }
    }
    private void update_to_expired(){
        String sql = "update drugs set EXPIRY='Expired' where BARCODE='"+expired_bar+"' ";
        try{
            pre=con.prepareStatement(sql);
            pre.execute();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }
    }
    private void login_as(){
        Date d = new Date();
        SimpleDateFormat dd = new SimpleDateFormat("hh:mm:ss");
  //      String sql = "insert into login (NAME,TYPE,DATE,TIME) values ('"+username1.getText()+"' ,'"+username.getText()+"' ,'"+today.getText()+"' ,'"+dd.format(d)+"' )";
        try {
 //           pre=con.prepareStatement(sql);
            pre.execute();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }
    }
    
    private void alert_message(){
  //      String sql = "select MESSAGE_TO,MESSAGE_FROM,MESSAGE_TEXT from message_history where MESSAGE_TO='"+username1.getText()+"' ";
        try{
   //         pre=con.prepareStatement(sql);
            res=pre.executeQuery();
            if(res.next()){
                to=res.getString("MESSAGE_TO");
                from=res.getString("MESSAGE_FROM");
                text=res.getString("MESSAGE_TEXT");
   //             msgAlertDialog.setVisible(true);
            }else{
   //             msgAlertDialog.setVisible(false);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }
    }
    
    private void deleteMsg(){
        String sql = "delete from message_history";
        try {
            pre=con.prepareStatement(sql);
            pre.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }
    }
}



