/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.userinterface;

import Business.EcoSystem;
import Business.UserAccount.UserAccountDirectory;
import Business.Citizen.CitizenDirectory;
import Business.userinterface.SystemAdminWorkArea.RegisterCitizen;
import Business.userinterface.SystemAdminWorkArea.ViewAllCitizen;
import java.awt.CardLayout;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author Pranav
 */
public class GuestUserJPanel extends javax.swing.JPanel {
EcoSystem system;
JPanel container;
UserAccountDirectory user_Dir;
CitizenDirectory Citizen_Di;
    /**
     * Creates new form GuestUserJPanel
     */
    public GuestUserJPanel() {
        initComponents();
    }

   
    GuestUserJPanel(JPanel container, EcoSystem system, CitizenDirectory Citizen_Di, UserAccountDirectory user_Dir) {
         initComponents();
       this.system =  system;
       this.Citizen_Di =Citizen_Di;
       this.user_Dir= user_Dir;
       this.container=container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegisterCitizen = new javax.swing.JButton();
        btnViewAllCitizen = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Guest User Dashboard");

        btnRegisterCitizen.setBackground(new java.awt.Color(255, 204, 51));
        btnRegisterCitizen.setText("Register Citizen");
        btnRegisterCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCitizenActionPerformed(evt);
            }
        });

        btnViewAllCitizen.setBackground(new java.awt.Color(255, 204, 51));
        btnViewAllCitizen.setText("View and track Citizens");
        btnViewAllCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllCitizenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnRegisterCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnViewAllCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(103, 103, 103)
                .addComponent(btnRegisterCitizen)
                .addGap(23, 23, 23)
                .addComponent(btnViewAllCitizen)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCitizenActionPerformed
        // TODO add your handling code here:
        RegisterCitizen rg = new RegisterCitizen(container,system, Citizen_Di, user_Dir);
        container.add("RegisterCitizen", rg);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnRegisterCitizenActionPerformed

    private void btnViewAllCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllCitizenActionPerformed
        // TODO add your handling code here:
        ViewAllCitizen rg = new ViewAllCitizen(container, system, Citizen_Di);
        container.add("ViewAllCitizen", rg);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewAllCitizenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterCitizen;
    private javax.swing.JButton btnViewAllCitizen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
